/*
    For this project, you will build a message generator program. Every time a user runs a program, they should get a new, 
    randomized output. 
*/

function generatorOfRandomNumber(num) {
    return Math.floor(Math.random() * num);
}


// a message object with 3 properties setup punchline, and ba dum tss.
// I am allowing the punchline to be mixed up with the wrong setup for adder humor.
// ha ha ha!!!!!!!!!!
// “Multiple exclamation marks,' he went on, shaking his head, 'are a sure sign of a diseased mind.” ― Terry Pratchett, Hogfather

const message = {
    setup: ["What do you call a bear with no teeth?", "What do you call a cow with no legs?", "What do you call a dog that does magic tricks?"],
    punchline: ["A gummy bear!", "Ground beef!", "Pork chop!", "A labracadabrador!"],
    baDumTss: ["Ba dum tss!"]
}

// create a function that will generate a random message from the message object
function generateMessage() {
    // create a variable that will store the random number generated by the generatorOfRandomNumber function
    let randomNumber = generatorOfRandomNumber(message.setup.length);
    // create a variable that will store the random message generated by the message object
    let randomMessage = message.setup[randomNumber] + " " + message.punchline[randomNumber] + " " + message.baDumTss[randomNumber];
    // return the random message
    return randomMessage;
}

// call the generateMessage function and store the result in a variable
let randomJoke = generateMessage();
// log the random message to the console
console.log(randomJoke);
